image: python:3.8.11-slim

stages:
  - unit_test_non_slow
  - unit_test_slow
  - pre
  - build

run_non_slow_unit_tests:
  stage: unit_test_non_slow
  script:
    - apt-get update
    - apt-get -y install build-essential
    - apt-get update
    - pip install -e .
    - pip install -r requirements_extra.txt
    - pip install -U pytest
    - python -m nltk.downloader punkt
    - echo 'Execute not slow unit tests'
    - pytest -m 'not slow' tests/

run_slow_unit_tests:
  stage: unit_test_slow
  when: manual
  needs:
    - run_non_slow_unit_tests
  script:
    - apt-get update
    - apt-get -y install build-essential
    - apt-get update
    - pip install -e .
    - pip install -r requirements_extra.txt
    - pip install -U pytest
    - python -m nltk.downloader punkt
    - echo 'Execute not slow unit tests'
    - pytest -m slow tests/

generate_demo_api_yaml:
  stage: pre
  image: alpine:latest
  script:
    - apk add -U jsonnet
    - jsonnet jsonnet/demo-api.jsonnet > generated-config.yml
  artifacts:
    paths:
      - generated-config.yml

generate_dev_demo_api_yaml:
  stage: pre
  image: alpine:latest
  script:
    - apk add -U jsonnet
    - jsonnet jsonnet/dev-demo-api.jsonnet > generated-config.yml
  artifacts:
    paths:
      - generated-config.yml


build_and_push_demo_api:
  stage: build
  allow_failure: true
  needs:
    - generate_demo_api_yaml
  trigger:
    include:
      - artifact: generated-config.yml
        job: generate_demo_api_yaml

build_and_push_dev_demo_api:
  stage: build
  allow_failure: true
  needs:
    - generate_dev_demo_api_yaml
  trigger:
    include:
      - artifact: generated-config.yml
        job: generate_dev_demo_api_yaml